### ISSUE TITLE
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/task/ctransformers/lib/avx2/libctransformers.so)

### ISSUE THREAD

**Issue by ravitejarao20** [marella/ctransformers#100] opened 2023-08-22 10:04 UTC
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/task/ctransformers/lib/avx2/libctransformers.so)

**Comment by marella** [comment] 2023-08-27 12:31
Duplicate of #41, #58

Please see https://github.com/marella/ctransformers/issues/41#issuecomment-1656734349 and https://github.com/marella/ctransformers/issues/58#issuecomment-1656702193

**Closed by marella** 2023-08-27 12:31 UTC
